[package]
name = "gen_parser"
version = "0.1.0"
authors = ["Joel Courtney <joel.e.courtney@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gen_parser_macro = { path = "/Users/joel/repos/gen_parser_macro" }