[package]
name = "gen_parser_macro"
version = "0.1.0"
authors = ["Joel Courtney <joel.e.courtney@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.73", features = ["full"] }
proc-macro2 = "1.0.27"
quote = "1.0.9"
proc-macro-error = "1.0.4"

[lib]
proc-macro = true